---
title: Events
---

### Upcoming

No upcoming events.

### Past

- 21-29 May 2021 [7th annual Wild/Feral Food Week](https://forage.berkeley.edu/7th-wild-feral-food-week/)
- 22-29 May 2020 [6th annual Wild/Feral Food Week](https://forage.berkeley.edu/6th-wild-feral-food-week/)
- 12 October 2019. [Seismic Salad: Fresh Food After “The Big One.” ](https://allevents.in/berkeley/seismic-salad-fresh-food-after-the-big-one/1000072713561219)
- 5/24/2019–5/31/2019. [5th Wild/Feral Food Week!](https://forage.berkeley.edu/5th-wild-feral-food-week/)
- 5/17/2019–5/19/2019. [2nd Health from the Soil Up Learning Lab](https://www.eventbrite.com/e/health-from-the-soil-up-learning-lab-tickets-60137097678)
- 5/18/2018–5/27/2018. [4th Wild/Feral Food Week!](https://forage.berkeley.edu/wild-and-feral-food-week-2018/)
- 9/16/17, noon-1:30pm. Foraging walk in North Berkeley with FoodInno
- 4/16/2017–4/22/2017: [3rd Annual Wild/Feral Food Week](http://forage.berkeley.edu/wild-feral-food-week-2017/).[Restaurants and Events](https://forage.berkeley.edu/wild-feral-food-week-2017/restaurants/);[Farms, Foragers, & Suppliers](https://forage.berkeley.edu/wild-feral-food-week-2017/farms/)This week will include an edible plant identification walk with the Berkeley Path Wanderers Association on 4/22. There are [22 innovative restaurants](https://forage.berkeley.edu/wild-feral-food-week-2017/restaurants/) in four states and two countries at a variety of price points, and numerous [growers, foragers, and other suppliers](https://forage.berkeley.edu/wild-feral-food-week-2017/farms/).
- 4/22/2017 [Where the Wild Things Grow](http://berkeleypaths.org/events/event/where-the-wild-things-grow-2/), wild/feral plant identification walk with the Berkeley Path Wanderers Association. Meet at Codornices Park, 10am, for a 3-mile hilly walk to see what wild and feral foods are volunteering abundantly in Berkeley.
- 3/9/2017: [Edible Weeds Tour of South Hayward](http://www.libraryinsight.com/eventdetails.asp?jx=hzp&lmx=%C7cn%2D%AA%AE&v=3), 2–4pm, Hayward Seed Lending Library, Hayward, CA
- 4/17/2016–4/23/2016: [2nd Annual Wild & Feral Food Week](http://forage.berkeley.edu/wildFoodWeek2016-4-17.htm) in Berkeley, San Francisco, and Sonoma County. This week will include an edible plant identification walk on the UC Berkeley Campus on 4/22 (12pm at the Campanile) and events at The Perennial (4/18), Chez Panisse (4/19), sweetgreen (4/20), Backyard (4/21), brown’s cafe (4/22), and Mission Heirloom (4/23), with menus that feature local wild and feral foods.
- 5/9/2015: WILD Oakland event, Edible Weeds in Oakland, 12–2pm. [http://wildoakland.org/event/edible-weeds/?instance_id=384](http://wildoakland.org/event/edible-weeds/?instance_id=384) Report: [http://wildoakland.org/2015/05/edible-urban-weeds-oaklands-sidewalk-salads/](http://wildoakland.org/2015/05/edible-urban-weeds-oaklands-sidewalk-salads/)
- 4/11/2015: Edible weed identification in the Peralta Community Garden, [https://communitygarden.org/find-a-garden/gardens/peralta-community-garden/](https://communitygarden.org/find-a-garden/gardens/peralta-community-garden/)
- 4/4/2015–4/10/2015: [Wild Food Week](http://forage.berkeley.edu/wildFoodWeek2015-4-4.htm) in Berkeley and San Francisco. This week will include an edible plant identification walk with the Berkeley Path Wanderers Association, [Where the Wild Things Grow](http://berkeleypaths.org/events/event/where-the-wild-things-grow/) and [special events](http://forage.berkeley.edu/wildFoodWeek2015-4-4.htm) at Cesar (4/4), Mission Chinese + The Perennial (4/8), Chez Panisse (4/9), and Mission Heirloom (4/10), with menus that feature local wild and feral foods.