---
title: "Inedible Species"
---

:::: {.grid}

::: {.g-col-8}


We’ve found relatively few inedible or toxic species that resemble edible species in the East Bay. Here they are:



- Chickweed (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Stellaria+media" class="edible-highlight"><em>Stellaria media</em></a>) looks like Scarlet Pimpernel (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Anagallis+arvensis" class="inedible-highlight"><em>Anagallis arvensis</em></a>). Chickweed has a single row of hairs along the stem, and white flowers. Scarlett pimpernel has scarlet flowers (coral-red), and the stems have hairs all around (not just in a single row).
- Cow parsnip (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Heracleum+maximum" class="edible-highlight"><em>Heracleum maximum</em></a>) might be confused with Poison hemlock (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Conium+maculatum" class="inedible-highlight"><em>Conium maculatum</em></a>). They don’t look extremely similar, but Poison hemlock is one of the most poisonous plants in the Bay Area, so be cautious!
- Mallow (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Malva+neglecta" class="edible-highlight"><em>Malva neglecta</em></a> and <a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Malva+sylvestris" class="edible-highlight"><em>Malva sylvestris</em></a>) looks like geranium (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Pelargonium+hirsutum" class="inedible-highlight"><em>Pelargonium hirsutum</em></a> and <a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Pelargonium+cucullatum" class="inedible-highlight"><em>Pelargonium cucullatum</em></a>). Mallow leaves are more delicate and unctuous; their flavor is mild. They don’t have much scent if you crush them. The flowers are generally bluish, pink, or white. Pelargonium leaves are very pungent and herbal if you crush them. The stems are thicker than mallow stems, and they have far more flowers than mallow, often red, pink, or purple in the Bay Area.
- The leaves of oxeye daisy (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Leucanthemum+vulgare" class="edible-highlight"><em>Leucanthemum vulgare</em></a>) look somewhat similar to the leaves of Groundsel (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Senecio+vulgaris" class="inedible-highlight"><em>Senecio vulgaris</em></a>). Both are in the family Asteracea.
- Pennyroyal (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Mentha+pulegium" class="inedible-highlight"><em>Mentha pulegium</em></a>) can cause liver damage and death. It smells like spearmint (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Mentha+spicata" class="edible-highlight"><em>Mentha spicata</em></a>) or coyote mint (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Monardella+villosa" class="edible-highlight"><em>Monardella villosa</em></a>) and the flowers look like those of purple sage (<a href="https://www.calflora.org/cgi-bin/specieslist.cgi?namesoup=Salvia+leucophylla" class="edible-highlight"><em>Salvia leucophylla</em></a>), but smaller.

:::

::: {.g-col-4}
{{< include sidebar.qmd >}}
:::

::::