---
title: Press
---

:::: {.grid}

::: {.g-col-8}

 - [Forager, runner, election auditor: This expert seeks answers on the trail](https://news.berkeley.edu/2023/07/05/forager-runner-election-auditor-this-expert-seeks-answers-on-the-trail), Jason Pohl, *Berkeley News*, 5 July 2023.
 - [The Abundance of Forageable Urban Greens](https://food.berkeley.edu/from-the-field/the-abundance-of-forageable-urban-greens/), Sarah Siegel, *Berkeley Food Institute*, 22 March 2023.
 - [AHA News: Foraging for Food Connects You to Nature – But Do Your Homework Before You Eat](https://www.usnews.com/news/health-news/articles/2021-12-02/aha-news-foraging-for-food-connects-you-to-nature-but-do-your-homework-before-you-eat), Will Pry, *USA Today*, 2 December 2021.
 - [Could weeds be the future of food? This urban forager thinks so](https://www.today.com/tmrw/could-weeds-be-future-food-urban-forager-thinks-so-t196786), Erica Chayes Wida, *Today*, 12 November 2020.
 - [Can I eat weeds in toxic soil?](https://yogahealer.com/can-i-eat-weeds-in-toxic-soil-with-dr-philip-stark-guest-dr-philip-stark/), *Yogahealer Podcast* with Cate Stillman, September 2020.
 - [Eating our campus: Foraging in the face of the coronavirus](https://www.dailycal.org/2020/03/27/eating-our-campus-foraging-in-the-face-of-the-coronavirus/), Hannah Frances Johansson, *The Daily Cal*, 27 March 2020.
 - [Foraged SuperFoods: Professor Philip B. Stark on the Nutritional Power of Weeds](https://onblend.tealeaves.com/foraged-superfoods/), *OnBlend*, 2 February 2020.
 - [Wild: A State of Mind](https://www.thebotanist.com/features/our-community/philip-stark/), *The Botanist*, August 2019.
 - [Open Your Eyes: A Responsible Guide to Foraging](https://foodprint.org/blog/sustainable-foraging/), Giulia Pines, *FoodPrint*, 3 July 2019.
 - [The Story of Weeds](https://forager.org.uk/index.php?option=com_content&view=article&id=248), *WorldWild Podcast*, Forager Ltd., July 2019.
 - [Embracing Invasivory through Urban Foraging](https://naturexdesign.tealeaves.com/embracing-invasivory-through-urban-foraging/), *Tealeaves Folio*, 24 July 2019.
 - [Where the wild things are: This group in Berkeley makes a case for eating weeds](https://www.berkeleyside.com/2019/05/20/where-the-wild-things-are-this-group-in-berkeley-makes-a-case-for-eating-weeds), Cirrus Wood, *Nosh: Dishing on the East Bay*, *Berkeleyside*, 20 May 2019.
 - [Greens Gone Wild: Food From The Sidewalk](https://www.ijpr.org/post/greens-gone-wild-food-sidewalk), *The Jefferson Exchange*, Jefferson Public Radio, Ashland, OR, 16 May 2019. [audio](https://cpa.ds.npr.org/ksor/audio/2019/05/may_16_2019_hr_1a.mp3)
 - [Ripe for the Picking: Wild weeds may provide a new food source](https://blogs.plos.org/everyone/2019/04/12/wild-weeds-may-provide-new-food-source/), Glenn Jackson, *PLoS EveryONE*, 12 April 2019.
 - [Innovators Look To “Accidental Crops” as a Nutritious, Environmentally Friendly and Free Source of Food](https://ensia.com/articles/wild-greens/), Natalie Parletta, *Ensia*, 28 September 2018.
 - [Can Urban Soil Offer Edible Weeds Fit for Foraging?](https://civileats.com/2018/09/21/can-urban-soil-offer-edible-weeds-fit-for-foraging/), Eden Stiffman, *Civil Eats*, 21 September 2018.
 - [Weeds growing in poor city areas more nutritious than store-bought produce](https://cosmosmagazine.com/biology/weeds-growing-in-poor-city-areas-more-nutritious-than-store-bought-produce), Natalie Parletta, *Cosmos: The Science of Everything*, 13 August 2018.
 - [Are edible weeds the next food trend?](http://www.mercurynews.com/2017/07/16/is-picking-edible-weeds-off-the-streets-the-next-foodie-trend/), Devika Bansal, *San Jose Mercury News*, 16 July 2017.
 - [Foraging, an educational skill set that could one day be taught in public schools](http://piercepioneernews.com/11293/campus/11293/), Jessica Wyant, *The Pioneer*, 17 May 2017.
 - [There’s Probably a Salad’s Worth of Greens On Your City Block](http://www.bonappetit.com/story/urban-foraging-philip-stark), Glenn Jackson, *Bon Appetit / Healthy-ish*, 9 May 2017.
 - [Berkeley Open Source Food Week promotes foraging](http://www.ktvu.com/news/249730521-story), Gasia Mikaelian, *KTVU*, 20 April 2017.
 - [UC Berkeley professor shares love of edible, nutritious weeds](http://www.eastbaytimes.com/2017/03/24/hayward-professor-shares-love-of-edible-nutritious-weeds/), Rebecca Parr, *East Bay Times*, 24 March 2017.
 - [Instead of Pokémon, Try Using Your Smartphone To Catch Tasty Wild Edibles](https://food.good.is/articles/foragers-call-these-apps-the-tinder-for-wild-food?sid=tw08022016), Jill Neimark, *Good*, 2 August 2016.
 - [Foraged Food Trend Is Part Epicurean, Part Environmental](http://www.foodandnutrition.org/July-August-2016/Wild-Eats/), Kristen Rasmussen Vasquez, *Food and Nutrition*, July 2016.
 - [Eat your Weedies!](http://www.spur.org/publications/urbanist-article/2016-03-09/walking-oakland), Philip B. Stark, *The Urbanist*, Issue 549, February 2016.
 - [Is food foraged in cities safe to eat?](http://civileats.com/2015/11/11/is-urban-foraging-cities-safe-toeat-boston/), Christina Boyes, *Civil Eats*, 11 November 2015.
 - [Terra Verde interview](http://archives.kpfa.org/data/20150821-Fri1400.mp3), Jason Mark, *KPFA*, 21 August 2015.
 - [Un repas au coin du bitume](http://www.letemps.ch/Page/Uuid/e58f7054-3d24-11e5-9458-9f31f164eeae/Un_repas_au_coin_du_bitume), Julie Zaugg, *Le Temps*, 8 August 2015.
 - [Salad from the Sidewalk](http://www.nytimes.com/interactive/2015/07/09/opinion/09bittman.html), Philip B. Stark, *The New York Times*, 9 July 2015.
 - [A Walk on the Wild (Edibles) Side](http://www.nytimes.com/2015/07/09/opinion/mark-bittman-a-walk-on-the-wild-edibles-side.html), Mark Bittman, *The New York Times*, 9 July 2015.
 - [The Logistics of Urban Food Foraging](http://www.kcet.org/living/food/the-nosh/the-logistics-of-urban-food-foraging.html), Katherine Spiers, *KCET*, 8 July 2015.
 - [With apps in hand, foragers find food underfoot](http://rustikmagazine.com/technology-urban-foraging/), *Rustik Magazine*, 28 June 2015.
 - [Out of the Weeds](http://luckypeach.com/out-of-the-weeds/), *Lucky Peach*, 29 June 2015.
 - [Take a walk on the wild (edible) side](https://youtu.be/F8BLU3iaLgM), Mark Bittman, *California Matters*, 8 June 2015.
 - [California Matters: Mark Bittman’s Online Video Series Premieres with ‘Take a Walk on the Wild (Edibles) Side’](http://ww2.kqed.org/bayareabites/2015/06/08/california-matters-mark-bittmans-online-video-series-premieres-with-take-a-walk-on-the-wild-edibles-side/), Lisa Landers, *KQED*, 8 June 2015.
 - [Eat Your Weeds: Get outside and forage for your food in the forests and sidewalk cracks of the East Bay](http://www.eastbayexpress.com/oakland/eat-your-weeds/Content?oid=4289051), Sascha Bos, *East Bay Express*, 20 May 2015.
 - [Q&A: Philip Stark](http://ucfoodobserver.com/2015/05/11/qa-philip-stark/), Rose Hayden-Smith, *UC Food Observer*, 11 May 2015.
 - [Dandelions Should Be the New Kale](http://motherboard.vice.com/read/dandelions-should-be-the-new-kale), Emiko Jozuka, *Motherboard/Vice*, 27 April 2015.
 - [Salad at Your Feet](http://www.diablomag.com/May-2015/Salad-at-Your-Feet/), Nicholas Boer, *Diablo Magazine*, 27 April 2015.
 - [Weeds are the future of healthy eating](http://www.salon.com/2015/04/18/weeds_are_the_future_of_fine_dining_partner/), Jason Mark, *Salon.com*, 18 April 2015.
 - [Weed Eaters: Accompanying Berkeley’s Urban Foragers from Weed Patch to Dining Table](http://alumni.berkeley.edu/california-magazine/just-in/2015-04-15/weed-eaters-accompanying-berkeleys-urban-foragers-weed-patch), Kristine A. Wong, *California Magazine*, 15 April 2015.
 - [Up Front with Vylma V](https://kpfa.org/episode/up-front-april-9-2015/), *KPFA Radio*, 9 April 2015. (at 30:02)
 - [Bay Area restaurants are going wild for weeds](http://www.yourcentralvalley.com/story/d/story/bay-area-restaurants-are-going-wild-for-weeds/20261/ZaLYghuwfk2SA0o_phMXrw), *Your Central Valley*, 9 April 2015.
 - [Bay Area Restaurants Cooking Weeds for Wild Food Week](http://sanfrancisco.cbslocal.com/2015/04/08/bay-area-restaurants-cooking-weeds-wild-food-week/), Don Ford, *KPIX CBS News*, 8 April 2015.
 - [Weeds — They’re What’s for Dinner](http://www.earthisland.org/journal/index.php/elist/eListRead/weeds_theyre_whats_for_dinner/), Jason Mark, *Earth Island Journal*, 8 April 2015.
 - [The app that helps you discover edible weeds](http://www.bbc.com/news/technology-32124855), Richard Taylor, *BBC*, 8 April 2015.
 - [Wild Food Week Highlights Edible Weeds Going to Waste](http://www.nbcbayarea.com/news/local/Wild-Food-Week-298812881.html), Tamara Palmer, *NBC Bay Area News*, 6 April 2015.
 - [A Wild Food Week of Eating Weeds for Dinner](http://missionlocal.org/2015/04/for-wild-food-week-weeds-for-dinner/), Daniel Hirsch, *Mission Local*, 5 April 2015.
 - [Agroecology for Health and Nutrition: An Interview with Dr. Daphne Miller](https://foodtank.com/news/2014/12/agroecology-for-health-and-nutrition-an-interview-with-dr-daphne-miller/), *Food Tank*, December 2014.

:::

::: {.g-col-4}
{{< include sidebar.qmd >}}
:::

::::