---
title: 2nd Annual Wild/Feral Food Week
date: 2016-04-17
date-format: iso
---

Berkeley Open Source Food proudly presents the **Second Annual Wild/Feral Food Week**, a landmark culinary experience at some of the Bay Area's most innovative restaurants. This event highlights the culinary opportunity of "pandigenous" wild foods, reduces food and water waste, increases revenue to farmers, promotes farm biodiversity, and creates a supply chain and market for wild and feral foods.

Meals will feature foraged foods and ingredients harvested "between the rows" by our partner farms and suppliers, including [F.E.E.D. Sonoma](http://feedsonoma.com/), [Green String Farm](http://www.greenstringfarm.com/), [Holistic Ag](http://holisticag.com/), Honeycutt Farm, [The Living Wild Project](http://www.livingwild.org/), [Strong Arm Farm](http://www.strongarmfarm.com/), [Top Leaf Farms / Farm the Roof](http://www.topleaffarms.com/index.html), and [Veritable Vegetable](http://www.veritablevegetable.com/).

## Schedule

**April 17–23 (all week, except Tuesday)**  
[SHED Cafe](http://healdsburgshed.com/eat/shed-cafe/), 25 North Street, Healdsburg  
SHED will feature dishes in our cafe that include wild and foraged food all week (except Tuesday, when we are closed). Dinner service is from 5–9pm. [Reservations online](http://www.opentable.com/healdsburg-shed).

**April 18 (Monday)**  
[The Perennial](http://theperennialsf.com/), 59 Ninth Street, San Francisco  
Chef Chris Kiyuna will meld wild ingredients into The Perennial's sustainable progressive agrarian cuisine, which features perennial grains, produce from its own aquaponic farm, and meats grazed using "carbon farming" to sequester more carbon than they release. [Reservations online](http://www.opentable.com/the-perennial-reservations-san-francisco?rid=188047&restref=188047).

**April 19 (Tuesday)**  
[Chez Panisse](http://chezpanisse.com), 1517 Shattuck Ave, Berkeley (downstairs)  
Set menu. Chef Cal Peternell will seamlessly weave a variety of wild plants into the Chez Panisse experience.  
Reservations: (510) 548-5525 between 9:00 a.m. and 9:30 p.m., Monday through Saturday. A credit card is required to secure all reservations. The cancellation policy is one week prior to the reservation date, cancellations made less than one week ahead are subject to a $50 per person fee.

**April 20 (Wednesday)**  
[sweetgreen](http://sweetgreen.com/), 1890 Shattuck Ave., Berkeley  
sweetgreen is a destination for simple, seasonal, healthy food, and they're bringing salads and grain bowls to the Berkeley community with a new location at 1890 Shattuck Ave. in Berkeley.  
Opening day is April 19th, and 100% of proceeds are going to support nutrition education in the area.  
On April 20th, sweetgreen's Culinary Director, Michael Stebner, will celebrate Wild/Feral Food Week by replacing romaine lettuce with native weeds in their Falafel + Feta salad, which also contains broccoli leaf, feta from Belfiore, gluten-free falafel and a lemon garlic chili vinaigrette.

**April 20 (Wednesday)–April 23 (Saturday)**  
[Zatar Restaurant and Catering](http://www.zatarcatering.com/), 1981 Shattuck Ave., Berkeley  
Zatar will use foraged wild herbs and greens in our eclectic Mediterranean cuisine, including our most popular and traditional dishes: borekas, dolmas, kibbeh, soups and salads.

**April 21 (Thursday)**  
[Backyard](http://www.backyardforestville.com/), 6566 Front Street, Forestville  
Backyard will highlight and feature wild foods throughout their weekly, Thursday evening family-style fried chicken dinner. The three course dinner, for $36, will highlight the wild bounties of west county. There will be wild foods highlighted throughout the a la cart menu as well. Please visit [www.backyardforestville.com](http://www.backyardforestville.com/) for more information, or call 707-820-8445 for reservations.

**April 22 (Friday)**  
Wild Food Walk on the UC Berkeley campus with [Berkeley Open Source Food](http://forage.berkeley.edu/), starting at 12 noon at the Campanile.

[brown's: a california café](http://caldining.berkeley.edu/locations/on-campus-retail/pat-browns), UC Berkeley Genetics and Plant Biology Building  
To celebrate Earth Day and Wild & Feral Food Week, brown's café will be incorporating wild edible greens into their salads and other dishes throughout the day, in addition to holding an informal tasting event from 3—4pm. Get wild with us!

**April 23 (Saturday)**  
[Mission Heirloom](http://missionheirloom.com), 2085 Vine St, Berkeley  
On Saturday night, Mission:Heirloom becomes *Taqueria la Preservación*, a tale of native plants!  
Last year's event left no doubt in our mind that this is a singular culinary experience, where an incredible array of delicious, local wild foods are experienced at their best.  
Traditional ways of preserving food, like pickling, drying and making tinctures are an important part of the sustainability we are trying to achieve with wild food. Preservation is an important subject for us, and we think tacos are undeniably the most fun way to showcase these wild harvested ingredients and let people see how easy and fun it is to incorporate foraged foods on a daily basis. Yep, we're talking about those nutrient dense greens, flowers and berries that can be found in most urban gardens in the Bay Area, that most people consider "weeds." [Tickets $50 online](http://m-h-counterbasics.myshopify.com/collections/frontpage/products/taqueria-la-preservacion-a-tale-of-native-plants-dinner).

---

Please [donate to Berkeley Open Source Food](http://give.berkeley.edu/BOSF) to support our mission!

