---
title: 3rd Annual Wild/Feral Food Week 2017
date: 2017-04-16
date-format: iso
categories:
  - wild-feral
---

## Restaurants and Events | Farms, Foragers, & Suppliers

Berkeley Open Source Food proudly presents the **Third Annual Wild/Feral Food Week** (16–22 April 2017), a landmark culinary experience at some of the world's most innovative restaurants. This event highlights the culinary opportunity of "pandigenous" wild foods, reduces food and water waste, increases revenue to farmers, promotes farm biodiversity, and creates a supply chain and market for wild and feral foods.

Meals will feature foraged foods and ingredients harvested "between the rows" by our partner farms, foragers, and suppliers, including:

- [Backyard](https://www.backyardforestville.com/) (Forestville, CA)
- [F.E.E.D. Sonoma](https://feedsonoma.com/) (Sebastopol, CA)
- Five Springs Farm (Petaluma, CA)
- [Feral Heart Farm](https://feralheartfarm.squarespace.com) (Sonol, CA)
- [The Ron Finley Project "Gangsta Garden"](https://ronfinley.com/the-ron-finley-project/) (South Central Los Angeles, CA)
- [Kiss The Ground Garden](https://www.kisstheground.com/garden/) (Venice, CA)
- [Live Oak Farm](https://feedsonoma.com/map/live-oak-farm/) (Petaluma, CA)
- [The Living Wild Project](https://www.livingwild.org/)
- [Marin Roots Farm](https://marinrootsfarm.wordpress.com/) (Marin County, CA)
- [Morchella Wild Foods](https://www.morchellawildfoods.com/) (San Francisco, CA)
- [Sonoma County Herb Exchange](https://www.sonomaherbs.org/herb-exchange) (Sebastopol, CA)
- [Strong Arm Farm](https://www.strongarmfarm.com/) (Healdsburg, CA)
- [Tennyson High School Farm](https://ths-haywardusd-ca.schoolloop.com/eat) (Hayward, CA)
- [Top Leaf Farms / Farm the Roof](https://www.topleaffarms.com/index.html) (Oakland, CA)

Confirmed participating restaurants include:

- [Chez Panisse](https://www.chezpanisse.com) (Berkeley, CA)
- [Agrodolce](https://www.agrodolceberkeley.com/) (Berkeley, CA)
- [Backyard](https://www.backyardforestville.com/) (Forestville, CA)
- [brown's](https://caldining.berkeley.edu/locations/on-campus-retail/pat-browns) (Berkeley, CA)
- [The Buck and Birch](https://www.buckandbirch.com/what-we-do) (Edinburgh, Scotland)
- [Guerilla Cafe](https://www.facebook.com/GuerillaCafeCA/) (Berkeley, CA)
- [The Cannery Cafe](https://www.haywardareahistory.org/cafe/) (Hayward, CA)
- [Dirt Candy](https://www.dirtcandynyc.com/) (New York, NY)
- [Fork](https://forkrestaurant.com/) (Philadelphia, PA)
- [Gjelina](https://www.gjelina.com/) (Venice, CA)
- [Gjusta](https://www.gjusta.com/) (Venice, CA)
- [GTA](https://www.gjelinatakeaway.com/) (Venice, CA)
- [Inver Restaurant](https://www.inverrestaurant.co.uk) (Loch Fyne, Argyll, Scotland)
- [Ippuku](https://www.ippukuberkeley.com/) (Berkeley, CA)
- [Laurel Restaurant](https://www.restaurantlaurel.com/) (Philadelphia, PA)
- [Mission Heirloom](https://www.missionheirloom.com/) (Berkeley, CA)
- [Ned Ludd](https://www.nedluddpdx.com/) (Portland, OR)
- [Norn](https://nornrestaurant.com/) (Edinburgh, Scotland)
- [Pizzaiolo](https://www.pizzaiolooakland.com/) (Oakland, CA)
- [sweetgreen](https://www.sweetgreen.com/) (Culver City, CA, location)
- [The Local Butcher Shop](https://thelocalbutchershop.com/) (Berkeley, CA)
- [The Tasting Kitchen](https://thetastingkitchen.com/) (Venice, CA)

**Details of the events, schedule, reservations, and more, coming soon!**

---

Please [donate to Berkeley Open Source Food](https://give.berkeley.edu/BOSF) to support our mission!
