---
title: 'Seismic Salad: Fresh Food After "The Big One."'
date: 2019-10-12
date-format: iso
---

At James Kenney Park, 1720 Eighth Street, Berkeley, CA.

[Register at allevents.in](https://allevents.in/berkeley/seismic-salad-fresh-food-after-the-big-one/1000072713561219).

A major earthquake in the Bay Area will interrupt the food supply by damaging transportation infrastructure and the electrical grid (no refrigeration). Grocery stores could empty rapidly, and your earthquake emergency kit may quickly be exhausted.

Fortunately, there is a ready supply of fresh, nutritious, delicious produce in your neighborhood: wild and feral edible plants.

Foraging won't meet all your dietary needs, but it can extend your emergency supplies and make them more palatable and nutritious. That canned tuna in your bug-out bag will be much more appetizing mixed with chopped wild onions and purple sage, on a bed of wild mustard and chickweed.

On this one-hour (gentle) walk, you will learn to identify a number of delicious, nutritious wild foods that grow in virtually every Bay Area neighborhood.

This guided walking tour will start at the Community Emergency Prep Fair taking place on Saturday, October 12 from 10 am - 3 pm in James Kenney Park, Berkeley. We will gather at noon near the entrance to the Fair (Look for signs reading "Urban Foraging Walk at Noon - Meet Here"), and walk from there.

Led by Philip B. Stark, [Berkeley Open Source Food](/).

Questions? Contact Gradiva Couzin at 415-341-2574.

Also check out other [Festivals in Berkeley](https://allevents.in/berkeley/festivals).
